# Generated by Django 2.1.7 on 2019-03-20 18:38

from django.db import migrations, models
import django.db.models.deletion
import foods.models
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FoodBackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=functools.partial(foods.models.make_filepath, *('image',), **{}))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_background_image', to='foods.Food')),
            ],
        ),
    ]
