# Generated by Django 2.1.7 on 2019-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbackgroundimage',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
