# Generated by Django 2.1.7 on 2019-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_access', 'Can access the manager panel'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
