# Generated by Django 2.1.7 on 2019-03-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190327_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('manager', 'Can access the manager features'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
