# Generated by Django 2.1.7 on 2019-03-22 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0002_foodbackgroundimage_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_service_clients', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_service_clients', to='foods.Food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_service_orders', to='service.FoodService')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='foodservice',
            unique_together={('client', 'food')},
        ),
    ]
